### ISSUE TITLE
Things to do for release

### ISSUE THREAD

**Issue by hanscg** [HENNGE/terraform-check#1]
Is there anything else I need to make sure before making this repo public?

I tested this in a rather roundabout way since Github Actions couldn't directly use action from a private repo:
https://github.com/HENNGE/shobo-support-viewer/pull/217

**Comment by FurqanHabibi** [comment]
From what I gather from looking at the code, seems like this supports multiple directories right?
If yes, we should reflect as such in the docs as well.

**Comment by hanscg** [comment]
The python code does support it, but the action itself doesn't support it since the input [cannot be a list of string. (yet)
](https://github.com/actions/toolkit/issues/184)It's possible to get the input as a string and then parse it (e.g. `<first_directory>,<second_directory>`), but I haven't implemented it yet.

Since there's a possibility that different directories require different terraform version, I prefer to have this action called per-directory.

**Comment by hanscg** [comment]
Oh, I guess it might work if the input is `<first_directory> <second_directory>`

**Comment by FurqanHabibi** [comment]
Yeah, it works using multiline input https://github.com/actions/toolkit/issues/184#issuecomment-1198653452

For terraform version, we could have similar multiple input for it as well. Setting just 1 will make all directories use the same version. Setting nothing is the same as setting 1 with `latest`.

**Comment by FurqanHabibi** [comment]
Although will need more implementation to support the different terraform versions 😅 
We can add that to future roadmap perhaps?

**Comment by hanscg** [comment]
Yeah, supporting different terraform version is more complicated as github workflow doesn't support looping ...
Might need to move the terraform setup part inside the python code as well.

I'd like to have the python code to be usable locally as well, so putting terraform setup inside it might cause conflicts when run locally.
Let's put that part on hold for now.

**Comment by hanscg** [comment]
Or maybe we can use tfenv instead of setup-terraform

**Comment by FurqanHabibi** [comment]
yes, just about to mention that. can use something like this https://github.com/rhythmictech/actions-setup-tfenv
