### ISSUE TITLE
Modify terraform plan output instead of doing terraform refresh

### ISSUE THREAD

**Issue by FurqanHabibi** [HENNGE/terraform-check#11]
This is an enhancement for the hide_refresh option. As explained in [this article](https://developer.hashicorp.com/terraform/cli/commands/refresh), running terraform refresh can be dangerous, as it will automatically update the state file. Some credentials misconfiguration for example can misled terraform to think that the resources do not exist, thereby emptying the state file.

I would suggest to just remove `Refreshing...` or `Reading...` lines from terraform plan outputs instead of performing terraform refresh. Here's an example taken from [this issue](https://github.com/hashicorp/terraform/issues/27214):
```shell
terraform plan | grep -v "Refreshing state...\|Reading...\|Read complete after"
```

**Comment by hanscg** [comment]
Reading the documentation for `terraform plan` I assumed it refreshes the state file beforehand, is it not the case? 🤔 

> [-refresh=false](https://developer.hashicorp.com/terraform/cli/commands/plan#refresh-false) - Disables the default behavior of synchronizing the Terraform state with remote objects before checking for configuration changes.

**Comment by FurqanHabibi** [comment]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/2734516/221734385-6f62b8ea-401f-461d-9c12-9cd8de789520.png">

It is a bit different than terraform refresh in that the state refreshing is done in-memory, and will only be applied to the state file when terraform apply is carried on. This is unlike terraform refresh where the state file will always be updated.
https://developer.hashicorp.com/terraform/tutorials/state/refresh

**Comment by FurqanHabibi** [comment]
Let me create one, maybe not today though 🙇
