### ISSUE TITLE
Streamline release process

### ISSUE THREAD

**Issue by jarviliam** [HENNGE/terraform-check#21]
# Summary

Due to this being a public action we should look into an easier release process that accounts for major/minor version changes on conventional commits.

- Enforce squash merging only to enforce a linear history
- Use conventional commits
- Add release-please to maintain a CHANGELOG.md file within the repository itself and handle bumping versions by commit

Let me know what you think

**Comment by hanscg** [comment]
Thank you for the suggestion!
It sounds good, I think `release-please` release strategy suits this repository.
I'll look into implementing it asap 🙇
